# Generated by Django 4.0.4 on 2022-05-02 02:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MissingPersonPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Please enter the slug that will identify this missing person post.",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "mp_name",
                    models.CharField(
                        help_text="Please enter the name of the missing person.",
                        max_length=300,
                        verbose_name="missing person's name",
                    ),
                ),
                (
                    "mp_height",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Please enter the height in centimeters of the missing person.",
                        null=True,
                        verbose_name="missing person's height",
                    ),
                ),
                (
                    "mp_physical_build",
                    models.CharField(
                        blank=True,
                        choices=[("S", "Slim"), ("R", "Regular"), ("H", "Heavy")],
                        help_text="Please enter the physical build of the missing person.",
                        max_length=1,
                        verbose_name="missing person's physical build",
                    ),
                ),
                (
                    "mp_complexion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BR", "Brown"),
                            ("LB", "Light brown"),
                            ("DB", "Dark brown"),
                            ("WH", "White"),
                            ("BL", "Black"),
                        ],
                        help_text="Please enter the complexion of the missing person.",
                        max_length=2,
                        verbose_name="missing person's complexion",
                    ),
                ),
                (
                    "mp_sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        help_text="Please enter the sex of the missing person.",
                        max_length=1,
                        verbose_name="missing person's sex",
                    ),
                ),
                (
                    "mp_dob",
                    models.DateField(
                        blank=True,
                        help_text="Please enter the date of birth of the missing person.",
                        null=True,
                        verbose_name="missing person's date of birth",
                    ),
                ),
                (
                    "mp_eyes_description",
                    models.CharField(
                        blank=True,
                        help_text="Please enter a description of the missing person's eyes.",
                        max_length=500,
                        verbose_name="missing person's eyes description",
                    ),
                ),
                (
                    "mp_hair_description",
                    models.CharField(
                        blank=True,
                        help_text="Please enter a description of the missing person's hair.",
                        max_length=500,
                        verbose_name="missing person's hair description",
                    ),
                ),
                (
                    "mp_outfit_description",
                    models.CharField(
                        blank=True,
                        help_text="Please enter a description of the missings person's outfit.",
                        max_length=500,
                        verbose_name="missing person's outfit description",
                    ),
                ),
                (
                    "mp_identifying_characteristics",
                    models.CharField(
                        blank=True,
                        help_text="Please enter a description of the missing person's identifying characteristics.",
                        max_length=500,
                        verbose_name="missing person's identifying characteristics",
                    ),
                ),
                (
                    "circumstances_behind_dissapearance",
                    models.CharField(
                        blank=True,
                        help_text="Please enter a description of the circumstances behind dissapearance.",
                        max_length=500,
                        verbose_name="circumstances behind dissapearance",
                    ),
                ),
                (
                    "missing_from",
                    models.CharField(
                        blank=True,
                        help_text="Please enter the place where the missing person was last seen.",
                        max_length=150,
                        verbose_name="missing from",
                    ),
                ),
                (
                    "missing_date",
                    models.DateField(
                        blank=True,
                        help_text="Please enter the date when the missing person was last seen on.",
                        null=True,
                        verbose_name="missing date",
                    ),
                ),
                (
                    "found",
                    models.BooleanField(
                        default=False,
                        help_text="Please enter whether the missing person has been found or not.",
                        verbose_name="has been found?",
                    ),
                ),
                (
                    "po_state",
                    models.CharField(
                        choices=[
                            ("MX-CMX", "Ciudad de Mexico"),
                            ("MX-AGU", "Aguascalientes"),
                            ("MX-BCN", "Baja California"),
                            ("MX-BCS", "Baja California Sur"),
                            ("MX-CAM", "Campeche"),
                            ("MX-COA", "Coahuila de Zaragoza"),
                            ("MX-COL", "Colima"),
                            ("MX-CHP", "Chiapas"),
                            ("MX-CHH", "Chihuahua"),
                            ("MX-DUR", "Durango"),
                            ("MX-GUA", "Guanajuato"),
                            ("MX-GRO", "Guerrero"),
                            ("MX-HID", "Hidalgo"),
                            ("MX-JAL", "Jalisco"),
                            ("MX-MEX", "Mexico"),
                            ("MX-MIC", "Michoacan de Ocampo"),
                            ("MX-MOR", "Morelos"),
                            ("MX-NAY", "Nayarit"),
                            ("MX-NLE", "Nuevo Leon"),
                            ("MX-OAX", "Oaxaca"),
                            ("MX-PUE", "Puebla"),
                            ("MX-QUE", "Queretaro"),
                            ("MX-ROO", "Quintana Roo"),
                            ("MX-SLP", "San Luis Potosi"),
                            ("MX-SIN", "Sinaloa"),
                            ("MX-SON", "Sonora"),
                            ("MX-TAB", "Tabasco"),
                            ("MX-TAM", "Tamaulipas"),
                            ("MX-TLA", "Tlaxcala"),
                            ("MX-VER", "Veracruz de Ignacio de la Llave"),
                            ("MX-YUC", "Yucatan"),
                            ("MX-ZAC", "Zacatecas"),
                        ],
                        help_text="Please enter the state of the prosecutor's office.",
                        max_length=6,
                        verbose_name="prosecutor's office state",
                    ),
                ),
                (
                    "po_post_url",
                    models.URLField(
                        help_text="Please enter the URL of the missing person's post located on the prosecutor's office website.",
                        max_length=500,
                        verbose_name="prosecutor's office post's URL",
                    ),
                ),
                (
                    "po_post_publication_date",
                    models.DateField(
                        blank=True,
                        help_text="Please enter the date when the missing person's post was published on the prosecutor's office website.",
                        null=True,
                        verbose_name="prosecutor's office post's publication date",
                    ),
                ),
                (
                    "po_poster_url",
                    models.URLField(
                        blank=True,
                        help_text="Please enter the URL of the missing person's poster located on the prosecutor's office website.",
                        max_length=500,
                        verbose_name="prosecutor's office poster URL",
                    ),
                ),
                (
                    "is_multiple",
                    models.BooleanField(
                        default=False,
                        help_text="Please enter wheter the prosecutor's office post includes more than 1 person on it.",
                        verbose_name="is more than 1 person?",
                    ),
                ),
            ],
            options={
                "verbose_name": "missing person post",
                "verbose_name_plural": "missing person posts",
            },
        ),
    ]
