# Generated by Django 4.0.4 on 2022-05-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Please enter the last time this counter was updated.",
                        verbose_name="updated at",
                    ),
                ),
            ],
            options={
                "verbose_name": "counter",
                "verbose_name_plural": "counters",
            },
        ),
    ]
