# Generated by Django 4.0.4 on 2022-05-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counters", "0002_missingpersonpost_alert_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="missingpersonpost",
            name="mp_age_when_disappeared",
            field=models.SmallIntegerField(
                blank=True,
                help_text="Please enter the age the missing person had when they disappeared.",
                null=True,
                verbose_name="missing person's age when disappeared",
            ),
        ),
        migrations.AddField(
            model_name="missingpersonpost",
            name="mp_weight",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Please enter the weight in kilograms of the missing person.",
                null=True,
                verbose_name="missing person's weight",
            ),
        ),
    ]
