# Generated by developer on 2022-05-12 23:01

from django.db import migrations


def add_counter(apps, schema_editor):
    """Adds a Counter entity to the database."""
    Counter = apps.get_model("counters", "Counter")
    Counter.objects.create()


class Migration(migrations.Migration):
    dependencies = [
        ("counters", "0002_counter"),
    ]
    operations = [
        migrations.RunPython(add_counter),
    ]
