# Generated by Django 4.0.4 on 2022-06-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counters", "0003_populate_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missingpersonposter",
            name="alert_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AL", "Alba"),
                    ("AM", "Amber"),
                    ("HV", "Has visto a...?"),
                    ("OD", "Odisea"),
                    ("OT", "Other"),
                ],
                help_text="Please enter the alert or protocol type of this missing person poster.",
                max_length=2,
                verbose_name="alert type",
            ),
        ),
        migrations.AlterField(
            model_name="missingpersonposter",
            name="mp_sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                help_text="Please enter the sex of the missing person.",
                max_length=1,
                verbose_name="missing person's sex",
            ),
        ),
    ]
