# Generated by Django 4.0.4 on 2022-06-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counters", "0004_alter_missingpersonposter_alert_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missingpersonposter",
            name="alert_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AL", "Alba"),
                    ("AM", "Amber"),
                    ("HV", "Has visto a...?"),
                    ("OD", "Odisea"),
                ],
                help_text="Please enter the alert or protocol type of this missing person poster.",
                max_length=2,
                verbose_name="alert type",
            ),
        ),
    ]
