# Generated by Django 4.0.4 on 2022-06-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counters", "0005_alter_missingpersonposter_alert_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missingpersonposter",
            name="mp_complexion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VL", "Very light"),
                    ("L", "Light"),
                    ("LI", "Light intermediate"),
                    ("DI", "Dark intermediate"),
                    ("D", "Dark"),
                    ("VD", "Very dark"),
                ],
                help_text="Please enter the complexion of the missing person (see Von Luschan's skin color scale for more information).",
                max_length=2,
                verbose_name="missing person's complexion",
            ),
        ),
    ]
